Repository Workiva/react-dart, pull requests merged in 2021-01, with the labels that each got.

#296 Set up Workiva Build, move build steps since Travis which no longer runs
  .travis.yml
  Dockerfile
  dart_test.yaml
  test/factory/common_factory_tests.dart
  test/factory/dart_function_factory_test.dart
  test/lifecycle_test/util.dart
Labels: Merge Requirements Met, semver: Patch

#299 [6.0.0] Resolve peerDependencies warning for react-redux
  lib/react.js
  lib/react.js.map
  lib/react_dom.js
  lib/react_dom.js.map
  lib/react_dom_prod.js
  lib/react_dom_prod.js.map
  lib/react_prod.js
  lib/react_prod.js.map
  lib/react_with_addons.js
  lib/react_with_addons.js.map
  lib/react_with_react_dom_prod.js
  lib/react_with_react_dom_prod.js.map
  package.json
  yarn.lock
Labels: Merge Requirements Met, semver: Patch

#297 Set up Github actions CI
  .github/workflows/dart_ci.yml
  Dockerfile
  README.md
Labels: Merge Requirements Met, semver: Patch

#285 RM-93030 Release react-dart 6.0.0
  CHANGELOG.md
  README.md
  aviary.yaml
  js_src/_dart_helpers.js
  js_src/dart_env_dev.js
  js_src/react.js
  lib/react.dart
  lib/react.js
  lib/react.js.map
  lib/react_client.dart
  lib/react_client/component_factory.dart
  lib/react_dom.dart
  lib/react_dom.js
  lib/react_dom.js.map
  lib/react_dom_prod.js
  lib/react_dom_prod.js.map
  lib/react_dom_server.js
  lib/react_dom_server.js.map
  lib/react_dom_server_prod.js
  lib/react_dom_server_prod.js.map
  lib/react_prod.js
  lib/react_prod.js.map
  lib/react_with_addons.js
  lib/react_with_addons.js.map
  lib/react_with_react_dom_prod.js
  lib/react_with_react_dom_prod.js.map
  lib/src/react_client/event_factory.dart
  lib/src/react_client/event_helpers.dart
  lib/src/react_client/event_prop_key_to_event_factory.dart
  lib/src/react_client/factory_util.dart
  lib/src/react_client/synthetic_data_transfer.dart
  lib/src/react_client/synthetic_event_wrappers.dart
  package-lock.json
  package.json
  pubspec.yaml
  test/factory/common_factory_tests.dart
  test/js_builds/README
  test/js_builds/console_spy_include_this_js_first.js
  test/js_builds/js_dev_test.dart
  test/js_builds/js_dev_test.html
  test/js_builds/js_dev_with_addons_test.dart
  test/js_builds/js_dev_with_addons_test.html
  test/js_builds/js_prod_combined_test.dart
  test/js_builds/js_prod_combined_test.html
  test/js_builds/js_prod_test.dart
  test/js_builds/js_prod_test.html
  test/js_builds/shared_tests.dart
  test/js_interop_helpers_test/README
  test/js_interop_helpers_test/shared_tests.dart
  test/lifecycle_test.dart
  test/react_client/event_helpers_test.dart
  test/react_client/event_helpers_test.html
  test/react_client_test.dart
  test/react_test_utils_test.dart
  yarn.lock
Labels: InfoSec Review Required, Merge Requirements Met, RM Ready, semver: Major

#303 Fix bad aviary.yaml syntax
  Dockerfile
  aviary.yaml
Labels: InfoSec Review Required, Merge Requirements Met, semver: Patch
