Repository Workiva/react-dart, pull requests merged in 2023-10, with the labels that each got.

#372 FEDX-414 Add APIs and update deprecations in preparation for 7.0.0 release
  CHANGELOG.md
  lib/hooks.dart
  lib/react.dart
  lib/react_client.dart
  lib/react_client/component_factory.dart
  lib/react_client/react_interop.dart
  lib/src/react_client/component_registration.dart
  lib/src/react_client/dart_interop_statics.dart
  lib/src/react_client/event_helpers.dart
  lib/src/react_client/factory_util.dart
  lib/src/react_client/private_utils.dart
  test/hooks_test.dart
Labels: semver: Minor, Merge Requirements Met, RM Ready

#374 RM-215032 Release react-dart 6.3.0
  CHANGELOG.md
  lib/react_client/react_interop.dart
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#375 FED-1727 Remove the rest of the deprecated APIs for v7
  CHANGELOG.md
  lib/react.dart
  lib/react_client.dart
  lib/react_client/bridge.dart
  lib/react_client/component_factory.dart
  lib/react_client/react_interop.dart
  lib/src/react_client/component_registration.dart
  lib/src/react_client/dart_interop_statics.dart
  lib/src/react_client/event_helpers.dart
  lib/src/react_client/factory_util.dart
  lib/src/react_client/internal_react_interop.dart
  lib/src/react_client/private_utils.dart
  lib/src/react_client/synthetic_event_wrappers.dart
  test/factory/common_factory_tests.dart
  test/js_builds/shared_tests.dart
  test/react_memo_test.dart
Labels: Merge Requirements Met, RM Ready

#378 Dart 2.19
  Dockerfile
Labels: semver: Patch, Merge Requirements Met, RM Ready
